version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db   
    environment:
      POSTGRES_USER: alxuser
      POSTGRES_PASSWORD: alxpassword
      POSTGRES_DB: alxproperty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
